export type GlossaryCategory =
  | 'MDM'
  | 'Data Quality'
  | 'Data Integration'
  | 'Data Governance'
  | 'Data Sources'
  | 'Reverse Integration'
  | 'F&B / Hospitality'
  | 'Apparel'
  | 'Location'
  | 'Financial'
  | 'General';

export interface GlossaryTerm {
  term: string;
  definition: string;       // 1-2 sentences, practitioner-level
  category: GlossaryCategory;
  relatedSlug?: string;     // links to /topics/[slug] or /domains/[slug]
  relatedType?: 'topic' | 'domain';
  also?: string;            // "Also known as" abbreviation or alias
}

export const glossaryTerms: GlossaryTerm[] = [
  // ── MDM ──────────────────────────────────────────────────────────
  { term: 'Golden Record', definition: 'The single, authoritative, deduplicated representation of a master data entity — a customer, supplier, product, or location. The output of an MDM match/merge process.', category: 'MDM', relatedSlug: 'master-data-management', relatedType: 'topic' },
  { term: 'Match & Merge', definition: 'The MDM process of identifying records that refer to the same real-world entity (match) and combining them into a single golden record (merge). The hardest part is defining what "same" means.', category: 'MDM', relatedSlug: 'master-data-management', relatedType: 'topic' },
  { term: 'Survivor Rules', definition: 'The logic that determines which attribute values "survive" into the golden record when merging duplicate records — e.g., most recent, most complete, from most trusted source.', category: 'MDM', relatedSlug: 'master-data-management', relatedType: 'topic' },
  { term: 'Identity Resolution', definition: 'The process of determining whether two or more records refer to the same real-world entity, despite differences in format, spelling, or source system.', category: 'MDM', relatedSlug: 'master-data-management', relatedType: 'topic' },
  { term: 'D&B DUNS', definition: 'Dun & Bradstreet\'s Data Universal Numbering System — a unique 9-digit identifier for legal business entities worldwide. The de facto standard for linking supplier and customer records to a global entity hierarchy.', category: 'MDM', also: 'DUNS Number', relatedSlug: 'supplier', relatedType: 'domain' },
  { term: 'Hub-and-Spoke MDM', definition: 'An MDM architecture where a central hub holds the golden records and distributes them to spoke systems. Changes are governed at the hub; spokes are subscribers.', category: 'MDM', relatedSlug: 'master-data-management', relatedType: 'topic' },
  { term: 'Registry MDM', definition: 'An MDM style where the golden record lives in a central registry with cross-references to source systems, but source systems retain their own records. Less invasive than Hub-and-Spoke.', category: 'MDM' },
  { term: 'Source of Record', definition: 'The system designated as the authoritative source for a specific data attribute — not necessarily for all attributes of an entity. Different attributes may have different sources of record.', category: 'MDM', also: 'SOR' },
  { term: 'Parent-Child Hierarchy', definition: 'A hierarchical relationship between records of the same entity type — e.g., a supplier site (child) under a legal entity (parent) under an ultimate parent group. Critical for supply chain risk and consolidated reporting.', category: 'MDM', relatedSlug: 'supplier', relatedType: 'domain' },
  { term: 'Data Steward', definition: 'The person accountable for the quality and governance of a specific data domain or data asset. Not a data janitor — a steward defines standards, resolves disputes, and drives adoption.', category: 'MDM', relatedSlug: 'data-governance', relatedType: 'topic' },

  // ── Data Quality ──────────────────────────────────────────────────
  { term: 'Completeness', definition: 'A data quality dimension measuring whether all required fields are populated. A customer record missing an email address is incomplete — and unactivatable in most marketing systems.', category: 'Data Quality', relatedSlug: 'data-quality', relatedType: 'topic' },
  { term: 'Accuracy', definition: 'Whether a data value correctly reflects the real-world entity it represents. An address that was correct 3 years ago may now be inaccurate if the customer has moved.', category: 'Data Quality', relatedSlug: 'data-quality', relatedType: 'topic' },
  { term: 'Consistency', definition: 'Whether the same data attribute holds the same value across different systems. A customer with different date-of-birth values in the CRM and loyalty platform has a consistency issue.', category: 'Data Quality', relatedSlug: 'data-quality', relatedType: 'topic' },
  { term: 'Timeliness', definition: 'Whether data is available and current when it is needed. Real-time decisions require real-time data; batch feeds introduce lag that makes data stale for time-sensitive use cases.', category: 'Data Quality', relatedSlug: 'data-quality', relatedType: 'topic' },
  { term: 'Uniqueness', definition: 'The degree to which a record appears only once in a dataset. A low uniqueness score means high duplication — the primary driver of incorrect MDM outputs.', category: 'Data Quality', relatedSlug: 'data-quality', relatedType: 'topic' },
  { term: 'Validity', definition: 'Whether a data value conforms to the defined format, range, or reference set — e.g., a postcode must match a known postcode format; a status field must be one of a defined set of values.', category: 'Data Quality', relatedSlug: 'data-quality', relatedType: 'topic' },
  { term: 'Data Profiling', definition: 'The process of examining data to understand its structure, content, completeness, and quality. The first step of every serious data quality programme.', category: 'Data Quality', relatedSlug: 'data-quality', relatedType: 'topic' },
  { term: 'Null Rate', definition: 'The percentage of records where a specific field is null or empty. A null rate above 15–20% for a business-critical field is typically a red flag.', category: 'Data Quality' },
  { term: 'Duplicate Rate', definition: 'The percentage of records in a dataset that are duplicates of another record. In Customer data, duplicate rates of 10–30% are common before MDM is implemented.', category: 'Data Quality', relatedSlug: 'data-quality', relatedType: 'topic' },
  { term: 'Referential Integrity', definition: 'The guarantee that a foreign key reference in one table always points to an existing record in the referenced table. Broken referential integrity causes silent data loss in joins.', category: 'Data Quality' },
  { term: 'Data Cleansing', definition: 'The process of detecting and correcting (or removing) inaccurate, incomplete, or duplicate records from a dataset. A one-time act — without Governance, data degrades again.', category: 'Data Quality', also: 'Data Scrubbing', relatedSlug: 'data-quality', relatedType: 'topic' },
  { term: 'Conformity', definition: 'Whether data adheres to defined standards and formats — e.g., all dates in ISO 8601, all country codes in ISO 3166. Often the easiest DQ dimension to automate.', category: 'Data Quality' },

  // ── Data Integration ──────────────────────────────────────────────
  { term: 'ETL', definition: 'Extract, Transform, Load — data is extracted from source systems, transformed to meet target schema requirements, then loaded into a destination. The traditional data warehousing pattern.', category: 'Data Integration', also: 'Extract, Transform, Load', relatedSlug: 'data-integration', relatedType: 'topic' },
  { term: 'ELT', definition: 'Extract, Load, Transform — data is loaded raw into a destination (usually a cloud data warehouse) and transformed there. Enabled by cheap compute; preferred in modern data stacks.', category: 'Data Integration', also: 'Extract, Load, Transform', relatedSlug: 'data-integration', relatedType: 'topic' },
  { term: 'CDC', definition: 'Change Data Capture — a technique that identifies and captures only the changes (inserts, updates, deletes) in a source database, rather than extracting the full dataset each time.', category: 'Data Integration', also: 'Change Data Capture', relatedSlug: 'data-integration', relatedType: 'topic' },
  { term: 'Data Pipeline', definition: 'A sequence of automated data processing steps — extraction, transformation, validation, loading — that moves data from source to destination reliably and on schedule.', category: 'Data Integration', relatedSlug: 'data-integration', relatedType: 'topic' },
  { term: 'iPaaS', definition: 'Integration Platform as a Service — cloud-based middleware that connects applications and data sources via pre-built connectors and low-code integration flows. Examples: MuleSoft, Dell Boomi, Workato.', category: 'Data Integration', also: 'Integration Platform as a Service' },
  { term: 'Event-Driven Architecture', definition: 'An integration pattern where systems communicate by producing and consuming events in real-time, rather than polling or scheduled batch transfers. Enables genuine real-time data flows.', category: 'Data Integration', also: 'EDA' },
  { term: 'Data Mesh', definition: 'An organisational approach where domain teams own, produce, and serve their data as products, rather than centralising all data in a monolithic warehouse. Decentralises both data and accountability.', category: 'Data Integration' },
  { term: 'Data Fabric', definition: 'An architecture that provides a unified, consistent data access layer across disparate systems and environments — on-premise, cloud, hybrid — without necessarily moving the data.', category: 'Data Integration' },
  { term: 'API', definition: 'Application Programming Interface — a defined contract for how one system can request data or actions from another. The modern standard for real-time data exchange between operational systems.', category: 'Data Integration', relatedSlug: 'data-sources', relatedType: 'topic' },
  { term: 'Webhook', definition: 'A push-based integration mechanism where a source system sends data to a target URL whenever a specific event occurs — rather than the target polling the source for changes.', category: 'Data Integration' },
  { term: 'Batch Processing', definition: 'Processing data in bulk at scheduled intervals rather than in real-time. Still common for large-volume, latency-tolerant workloads but creates data lag for time-sensitive decisions.', category: 'Data Integration', relatedSlug: 'data-integration', relatedType: 'topic' },

  // ── Data Governance ───────────────────────────────────────────────
  { term: 'Data Owner', definition: 'The senior business leader accountable for a data domain — its quality, governance, and strategic use. Data owners set policy; data stewards enforce it.', category: 'Data Governance', relatedSlug: 'data-governance', relatedType: 'topic' },
  { term: 'RACI Matrix', definition: 'A governance tool that maps Responsible, Accountable, Consulted, and Informed roles to data management activities. The difference between governance that works and governance that looks good on paper.', category: 'Data Governance', relatedSlug: 'data-governance', relatedType: 'topic' },
  { term: 'Data Catalogue', definition: 'A metadata repository that documents what data exists, where it lives, who owns it, how it is defined, and how it flows. The navigational layer on top of a data estate.', category: 'Data Governance', relatedSlug: 'data-governance', relatedType: 'topic' },
  { term: 'Data Lineage', definition: 'The documented journey of data from its origin through all transformations to its current state. Essential for debugging data quality issues and satisfying regulatory audit requirements.', category: 'Data Governance', relatedSlug: 'data-governance', relatedType: 'topic' },
  { term: 'Metadata', definition: 'Data about data — describing its structure, origin, meaning, quality, and usage. Metadata makes data discoverable, trustworthy, and governable at scale.', category: 'Data Governance' },
  { term: 'PII', definition: 'Personally Identifiable Information — any data that can be used to identify a specific individual. Governed under GDPR, CCPA, and other data protection regulations with strict handling requirements.', category: 'Data Governance', also: 'Personally Identifiable Information', relatedSlug: 'data-governance', relatedType: 'topic' },
  { term: 'GDPR', definition: 'General Data Protection Regulation — the EU\'s primary data protection law. Mandates lawful basis for processing, data subject rights (including right to erasure), and significant fines for non-compliance.', category: 'Data Governance', relatedSlug: 'data-governance', relatedType: 'topic' },
  { term: 'Right to Erasure', definition: 'A GDPR right allowing individuals to request deletion of their personal data. Requires organisations to identify all systems holding that data — which is impossible without a customer golden record and data lineage.', category: 'Data Governance', also: 'Right to be Forgotten' },
  { term: 'Data Retention Policy', definition: 'A governance policy defining how long different categories of data should be kept, and how they should be disposed of at end-of-life. Balances regulatory compliance with storage cost.', category: 'Data Governance', relatedSlug: 'data-governance', relatedType: 'topic' },
  { term: 'Data Classification', definition: 'The process of categorising data by sensitivity level — e.g., Public, Internal, Confidential, Restricted — to determine appropriate access controls and handling procedures.', category: 'Data Governance' },
  { term: 'Business Glossary', definition: 'A governed dictionary of business terms and their agreed definitions — ensuring that "Revenue", "Customer", and "Active Store" mean the same thing to Finance, Marketing, and Operations.', category: 'Data Governance', relatedSlug: 'data-governance', relatedType: 'topic' },

  // ── Data Sources ──────────────────────────────────────────────────
  { term: 'Data Lake', definition: 'A central repository that stores raw, unprocessed data at any scale — structured, semi-structured, and unstructured. Flexible but prone to becoming an ungovernered "data swamp" without stewardship.', category: 'Data Sources', relatedSlug: 'data-sources', relatedType: 'topic' },
  { term: 'Data Warehouse', definition: 'A structured repository optimised for analytical queries — data is cleaned, transformed, and organised into schemas before storage. Slower to load than a data lake but faster and more reliable to query.', category: 'Data Sources', relatedSlug: 'data-sources', relatedType: 'topic' },
  { term: 'Data Lakehouse', definition: 'A modern architecture combining the low-cost storage of a data lake with the data management and query performance features of a warehouse. Platforms: Databricks Delta Lake, Apache Iceberg.', category: 'Data Sources' },
  { term: 'OLTP', definition: 'Online Transaction Processing — databases optimised for high-volume, low-latency transactional operations (insert, update, delete). The systems where business happens: ERP, CRM, POS.', category: 'Data Sources', also: 'Online Transaction Processing' },
  { term: 'OLAP', definition: 'Online Analytical Processing — databases optimised for complex analytical queries over large datasets. Where business intelligence happens: data warehouses, cube systems.', category: 'Data Sources', also: 'Online Analytical Processing' },
  { term: 'DaaS', definition: 'Data as a Service — third-party data delivered via API or periodic feed to enrich or supplement internal data. Examples: D&B (company data), Experian (consumer data), Nutritics (nutritional data), YEXT (location data).', category: 'Data Sources', also: 'Data as a Service', relatedSlug: 'data-sources', relatedType: 'topic' },
  { term: 'Data Latency', definition: 'The delay between when data is created in a source system and when it is available for use in a target system. Batch pipelines have hours of latency; streaming pipelines have seconds.', category: 'Data Sources', relatedSlug: 'data-sources', relatedType: 'topic' },

  // ── Reverse Integration ───────────────────────────────────────────
  { term: 'Reverse ETL', definition: 'The process of moving data from a data warehouse back to operational systems — CRMs, ad platforms, email tools — to activate analytics in real workflows. The "last mile" of data.', category: 'Reverse Integration', relatedSlug: 'reverse-integration', relatedType: 'topic' },
  { term: 'Data Activation', definition: 'Making clean, analytics-ready data available in the operational tools where business users actually work — salesforce, marketing platforms, customer support systems. Without activation, insights stay in dashboards.', category: 'Reverse Integration', relatedSlug: 'reverse-integration', relatedType: 'topic' },
  { term: 'Customer Data Platform', definition: 'A system that creates persistent, unified customer profiles from multiple sources and makes them available to other marketing and personalisation tools in real time.', category: 'Reverse Integration', also: 'CDP', relatedSlug: 'reverse-integration', relatedType: 'topic' },
  { term: 'Audience Sync', definition: 'Pushing a defined customer segment from a data warehouse or CDP into an advertising or marketing platform — enabling targeted campaigns based on warehouse-grade analytics.', category: 'Reverse Integration' },
  { term: 'Operational Analytics', definition: 'Using analytical data directly in operational workflows and systems — as opposed to in standalone BI dashboards. Requires reverse integration to close the loop from insight to action.', category: 'Reverse Integration', relatedSlug: 'reverse-integration', relatedType: 'topic' },

  // ── F&B / Hospitality ─────────────────────────────────────────────
  { term: 'Logistical Variant', definition: 'The purchasable form of an ingredient as it arrives from a supplier — distinct from how it appears in a recipe. "IQF Chicken Breast 5kg Bag" is a logistical variant; "Diced Chicken Breast 150g" is a recipe ingredient.', category: 'F&B / Hospitality', relatedSlug: 'product-hospitality', relatedType: 'domain' },
  { term: 'Menu Item', definition: 'The consumer-facing product in a hospitality context — name, description, price, photography, dietary badges. Not to be confused with the recipe (how it\'s made) or the logistical variant (how it\'s bought).', category: 'F&B / Hospitality', relatedSlug: 'product-hospitality', relatedType: 'domain' },
  { term: 'Recipe', definition: 'The ingredient-level breakdown of a menu item, including portion weights, yield factors, and cooking method. The bridge between what the customer orders and what the supplier delivers.', category: 'F&B / Hospitality', relatedSlug: 'product-hospitality', relatedType: 'domain' },
  { term: "Natasha's Law", definition: 'UK legislation (October 2021) requiring full ingredient and allergen labelling on all pre-packed-for-direct-sale food. A data management programme masquerading as a food safety law.', category: 'F&B / Hospitality', relatedSlug: 'product-hospitality', relatedType: 'domain' },
  { term: 'Allergen Declaration', definition: 'The formal statement of which of the 14 major allergens are present in a food product. Inaccurate allergen declarations are a data quality failure with life-critical consequences.', category: 'F&B / Hospitality', relatedSlug: 'product-hospitality', relatedType: 'domain' },
  { term: 'Portion Yield', definition: 'The expected output weight or volume from a recipe after cooking loss is accounted for. Raw weight ≠ served weight. Portion yield is the conversion factor for accurate food cost calculation.', category: 'F&B / Hospitality', relatedSlug: 'product-hospitality', relatedType: 'domain' },
  { term: 'Modifier', definition: 'A customer-requested customisation applied to a menu item at point of order — extra sauce, no onion, swap to oat milk. Modifiers affect allergen declarations, nutritional profiles, and recipe costs.', category: 'F&B / Hospitality', relatedSlug: 'product-hospitality', relatedType: 'domain' },

  // ── Apparel ───────────────────────────────────────────────────────
  { term: 'SKU', definition: 'Stock Keeping Unit — the atomic sellable product variant: style + colourway + size. A single style in 5 colours and 6 sizes generates 30 SKUs. Data management at SKU level is where range complexity lives.', category: 'Apparel', also: 'Stock Keeping Unit', relatedSlug: 'product-apparel', relatedType: 'domain' },
  { term: 'Style Master', definition: 'The golden record for a garment concept — the single authoritative record for a style across buying, merchandising, logistics, and retail. The MDM golden record for apparel product data.', category: 'Apparel', relatedSlug: 'product-apparel', relatedType: 'domain' },
  { term: 'Colourway', definition: 'A colour variant of a style, with canonical name and Pantone/hex reference. "Sage" and "Sage Green" might be the same colourway mis-entered twice — a classic data quality failure in apparel.', category: 'Apparel', relatedSlug: 'product-apparel', relatedType: 'domain' },
  { term: 'GTIN', definition: 'Global Trade Item Number — the international standard for product identification, encoded in barcodes and QR codes. Required for retail scanning, GS1 registration, and e-commerce listings.', category: 'Apparel', also: 'Global Trade Item Number', relatedSlug: 'product-apparel', relatedType: 'domain' },
  { term: 'PLM', definition: 'Product Lifecycle Management — software that manages the full lifecycle of a product from design concept through production and retirement. The source of record for product specifications in most apparel organisations.', category: 'Apparel', also: 'Product Lifecycle Management', relatedSlug: 'product-apparel', relatedType: 'domain' },
  { term: 'PIM', definition: 'Product Information Management — a system that centralises and enriches product data for commercial distribution to e-commerce, catalogues, and wholesale portals. The MDM hub for product content.', category: 'Apparel', also: 'Product Information Management', relatedSlug: 'product-apparel', relatedType: 'domain' },

  // ── Location ──────────────────────────────────────────────────────
  { term: 'Catchment Area', definition: 'The geographic zone from which a store or site draws the majority of its customers — typically defined as 5/10/20 minute isochrones by drive or walk. Fundamental to location-based analytics and new store feasibility.', category: 'Location', relatedSlug: 'location', relatedType: 'domain' },
  { term: 'Isochrone', definition: 'A geographic boundary representing equal travel time from a point — e.g., a 10-minute walk isochrone around a store. The analytical unit for catchment definition.', category: 'Location', relatedSlug: 'location', relatedType: 'domain' },
  { term: 'YEXT', definition: 'A location intelligence and digital listings management platform that syncs accurate location data (hours, address, attributes) to 200+ platforms including Google, Apple Maps, and Yelp from a single source of truth.', category: 'Location', relatedSlug: 'location', relatedType: 'domain' },
  { term: 'Trading Area', definition: 'The commercial zone around a site, defined by proximity or spend data — broader than catchment, used for competitive analysis, site selection, and range decisions.', category: 'Location', relatedSlug: 'location', relatedType: 'domain' },
  { term: 'Location Hierarchy', definition: 'The structured grouping of physical locations — Site → District → Region → Country → Division. The backbone of all location-based P&L, allocation, and operational reporting.', category: 'Location', relatedSlug: 'location', relatedType: 'domain' },

  // ── Financial ─────────────────────────────────────────────────────
  { term: 'Chart of Accounts', definition: 'The master reference list of all General Ledger accounts in an organisation\'s financial system. The most foundational reference data in finance — and the most contentious to govern post-acquisition.', category: 'Financial', also: 'CoA', relatedSlug: 'financial', relatedType: 'domain' },
  { term: 'Cost Centre', definition: 'The organisational unit to which costs are attributed for management accounting purposes. Must mirror the operational hierarchy (store, department, project) or every cost allocation is wrong.', category: 'Financial', relatedSlug: 'financial', relatedType: 'domain' },
  { term: 'Profit Centre', definition: 'A unit of commercial P&L accountability — a store, a product category, a channel. Requires clean location hierarchy and product hierarchy to produce meaningful results.', category: 'Financial', relatedSlug: 'financial', relatedType: 'domain' },
  { term: 'GL Account', definition: 'General Ledger Account — the atomic unit of financial recording. Every financial transaction maps to a GL account. Uncontrolled proliferation of GL accounts is the most common financial data governance failure.', category: 'Financial', relatedSlug: 'financial', relatedType: 'domain' },
  { term: 'Intercompany Elimination', definition: 'The accounting process of removing transactions between entities within the same group when producing consolidated financial statements — to avoid double-counting internal sales as group revenue.', category: 'Financial', relatedSlug: 'financial', relatedType: 'domain' },
  { term: 'Legal Entity', definition: 'A registered company with its own legal standing — the unit at which financial statements are produced and regulatory filings made. Post-acquisition entity hierarchy management is a major MDM challenge.', category: 'Financial', relatedSlug: 'financial', relatedType: 'domain' },
];
